# Generated by Django 2.1.7 on 2019-03-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CLAIMNO', models.CharField(max_length=200)),
                ('MEMONO', models.CharField(max_length=200)),
                ('CREATEYMD', models.CharField(max_length=200)),
                ('CREATEBY', models.CharField(max_length=200)),
                ('LINENO', models.CharField(max_length=200)),
                ('TEXT', models.CharField(max_length=200)),
                ('pub_date', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
