# Generated by Django 2.1.7 on 2019-03-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190322_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='CLAIMNO',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='CREATEBY',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='CREATEYMD',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='LINENO',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='MEMONO',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='claim',
            name='CLAIMANT',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='CLAIM_ID',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='COMMENTS',
            field=models.TextField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='PREDICTION',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='VERIFIED',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='TEXT',
            field=models.TextField(max_length=8000),
        ),
    ]
