# Generated by Django 2.1.7 on 2019-03-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190322_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='CUSTOMER',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
