# Generated by Django 2.1.7 on 2019-04-04 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20190322_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='CLAIMANT',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='CLAIM_ID',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='COMMENTS',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='CUSTOMER',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='INDICATOR',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='TEXT',
        ),
        migrations.RemoveField(
            model_name='claim',
            name='VERIFIED',
        ),
        migrations.AddField(
            model_name='claim',
            name='claimId',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='claimNumber',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='claimantName',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='customer',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='indicators',
            field=models.TextField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='noteDetails',
            field=models.TextField(default=' ', max_length=20000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claim',
            name='noteText',
            field=models.TextField(default=' ', max_length=5000),
            preserve_default=False,
        ),
    ]
