# Generated by Django 2.1.7 on 2019-04-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20190404_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchId', models.CharField(max_length=50)),
                ('claimNoteID', models.CharField(max_length=50)),
                ('claimNoteText', models.TextField(max_length=20000)),
                ('claimNoteType', models.CharField(max_length=50)),
                ('noteAdjuster', models.CharField(max_length=50)),
                ('noteDate', models.CharField(max_length=50)),
                ('supervisor', models.CharField(max_length=50)),
                ('indicators', models.TextField(max_length=200)),
                ('probability', models.CharField(max_length=10)),
                ('customer', models.CharField(max_length=50)),
                ('comments', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='claim',
            name='noteDetails',
        ),
    ]
