# Generated by Django 2.1.7 on 2019-04-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_note_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.CharField(max_length=50)),
                ('bill_id', models.CharField(max_length=50)),
                ('bill_line_id', models.CharField(max_length=50)),
                ('dos_from', models.CharField(max_length=50)),
                ('dos_to', models.CharField(max_length=50)),
                ('procedure_code', models.CharField(max_length=50)),
                ('procedure_modifier_code', models.CharField(max_length=50)),
                ('icd_code_1', models.CharField(max_length=50)),
                ('icd_code_2', models.CharField(max_length=50)),
                ('icd_code_3', models.CharField(max_length=50)),
                ('icd_code_4', models.CharField(max_length=50)),
                ('icd_code_5', models.CharField(max_length=50)),
                ('icd_code_6', models.CharField(max_length=50)),
                ('icd_code_7', models.CharField(max_length=50)),
                ('icd_code_8', models.CharField(max_length=50)),
                ('icd_code_9', models.CharField(max_length=50)),
                ('icd_code_10', models.CharField(max_length=50)),
                ('icd_code_11', models.CharField(max_length=50)),
                ('icd_code_12', models.CharField(max_length=50)),
                ('provider_charge', models.CharField(max_length=50)),
                ('units_of_service', models.CharField(max_length=50)),
                ('ppo_amount', models.CharField(max_length=50)),
                ('reduction_amount', models.CharField(max_length=50)),
                ('allowance', models.CharField(max_length=50)),
                ('paid_amount', models.CharField(max_length=50)),
                ('service_location', models.CharField(max_length=50)),
                ('specialty', models.CharField(max_length=50)),
                ('taxonomy_code', models.CharField(max_length=50)),
                ('lien', models.CharField(max_length=50)),
                ('npi', models.CharField(max_length=50)),
            ],
        ),
    ]
