# Generated by Django 2.1.7 on 2019-04-05 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='saving',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
