# Generated by Django 2.1.7 on 2019-04-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='claimNotePK',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
