# Generated by Django 2.1.7 on 2019-04-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_feedback_claimnotepk'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='reviewed',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
